//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acceso_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {

    
        public string CLI_CEDULA { get; set; }
        public string CLI_NOMBRE { get; set; }
        public string CLI_APELLIDO { get; set; }
        public string CLI_DIRECCION { get; set; }
        public string CLI_CORREO { get; set; }
        public string CLI_TELEFONO { get; set; }
        public string CLI_CONTRASENA { get; set; }

    }
}
