//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acceso_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        
    
        public string FAC_COD { get; set; }
        public string CLI_CEDULA { get; set; }
        public string VEN_CEDULA { get; set; }
        public Nullable<System.DateTime> FAC_FECHA { get; set; }
        public string FAC_ESTADO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual VENDEDOR VENDEDOR { get; set; }

    }
}
