//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acceso_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_FACTURA
    {
        public string PROD_CODIGO { get; set; }
        public string FAC_COD { get; set; }
        public Nullable<int> FP_CANTIDAD { get; set; }
        public Nullable<decimal> FP_PRECIO { get; set; }
    
        public virtual FACTURA FACTURA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
