//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acceso_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {

        public string PROD_CODIGO { get; set; }
        public string PROD_NOMBRE { get; set; }
        public string PROD_TIPO { get; set; }
        public string PROD_MARCA { get; set; }
        public Nullable<System.DateTime> PROD_CADUCIDAD { get; set; }
        public Nullable<decimal> PROD_PRECIOVEN { get; set; }
        public Nullable<decimal> PROD_PRECIOCOM { get; set; }
        public string PROD_IMAGEN { get; set; }

    }
}
