//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acceso_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {

    
        public string PROV_COD { get; set; }
        public string PROV_NOMEMP { get; set; }
        public string PROV_TELEFONO { get; set; }
        public string PROV_DIRECCION { get; set; }
        public string PROV_CORREO { get; set; }
        public string PROV_VENDEDOR { get; set; }
    

    }
}
